# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DevTUI
email: contactl@devtui.com
description: >- # this means to ignore newlines until "baseurl:"
  All-in-one terminal toolkit designed for developers. It consolidates your everyday utilities into a single, unified TUI (Text User Interface) and CLI (Command Line Interface). No more juggling multiple tools â€” everything you need is now just one command away.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devtui.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 5katkov
github_username: skatkov

author:
  fullname: Stanislav Katkov
  github: skatkov
  twitter: 5katkov

keep_files: ["assets/images/og"]

og_image:
  collections: ["pages"]
  output_dir: "assets/images/og"
  domain: "devtui.com"
  canvas:
    width: 1200
    height: 630
    background_color: "#ffffff"
  header:
    font_family: "monospace"
    color: "#1f2937"
  content:
    font_family: "sans-serif"
    color: "#6b7280"
  border_bottom:
    width: 8
    fill: ["#1f2937"]

defaults:
  - values:
      layout: "default"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-og-image
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

liquid:
  error_mode: strict
  strict_filters: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

enable_copy_code_button: true

favicon_ico: "/assets/img/favicon.ico"

aux_links:
  Github:
    - https://github.com/skatkov/devtui

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_footer_custom: ""

nav_enabled: true
